[versions]
composeMultiplatform = "1.10.0"
kotlin = "2.3.0"
typst = "0.8.0"
kotlinx-coroutines = "1.10.2"
material3 = "1.11.0-alpha01"
materialKolor = "5.0.0-alpha06"
navigation3 = "1.0.0-alpha06"
material3Adaptive = "1.3.0-alpha02"
kotlinx-serialization = "1.9.0"

[libraries]
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composeMultiplatform" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "composeMultiplatform" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMultiplatform" }
compose-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "composeMultiplatform" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "composeMultiplatform" }
materialKolor = {module = "com.materialkolor:material-kolor", version.ref = "materialKolor"}
navigation3-runtime = {module = "org.jetbrains.androidx.navigation3:navigation3-runtime", version.ref ="navigation3"}
navigation3-ui = {module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref ="navigation3"}
compose-material3-adaptive-navigation3 = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive-navigation3", version.ref = "material3Adaptive" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
compose-material3-adaptive = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive", version.ref = "material3Adaptive" }
compose-material3-adaptive-layout = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive-layout", version.ref = "material3Adaptive" }
compose-material3-adaptive-navigation-suite = { group = "org.jetbrains.compose.material3", name = "material3-adaptive-navigation-suite", version.ref = "material3" }



[plugins]
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform"}
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
typst = {id = "de.infolektuell.typst", version.ref="typst"}
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }